//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestaoVinho
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinhosEntities : DbContext
    {
        public VinhosEntities()
            : base("name=VinhosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casta> Castas { get; set; }
        public virtual DbSet<Enologo> Enologoes { get; set; }
        public virtual DbSet<Produtor> Produtors { get; set; }
        public virtual DbSet<Regiao> Regiaos { get; set; }
        public virtual DbSet<Vinho> Vinhoes { get; set; }
        public virtual DbSet<VinhoCasta> VinhoCastas { get; set; }
        public virtual DbSet<VinhoEnologo> VinhoEnologoes { get; set; }
    }
}
